---
deployment:
  tasks:
    - export DEPLOYPATH=/home/useradmin/api.mosaicandtiledepot.com/
    - /usr/local/cpanel/3rdparty/bin/git checkout --theirs .
    - /bin/cp main/.env.example main/.env
    - /usr/local/cpanel/3rdparty/bin/git config --global user.email "mdgrisalez@misena.edu.co"
    - /usr/local/cpanel/3rdparty/bin/git config --global user.name "angell007" .
    - /usr/local/cpanel/3rdparty/bin/git config --global user.password "Angell00-7" .
    - /usr/local/cpanel/3rdparty/bin/git add .
    - "echo 'Pre up files...'"
    # - /usr/local/cpanel/3rdparty/bin/git commit -m "changes in pro"
metadata:
    name: "App Qr"
    version: "1.0"
    author: "Danilo Grisalez"
post_deploy:
pre_deploy:
    - "echo 'Pre up files...'"
hooks:
  pre:
    - command: "echo 'Backing up files...'"
  post:
    - command: "echo 'Deployment complete.'"