name: Nombre de tu flujo de trabajo
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: https://hooks.slack.com/services/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
    if: always()
