name: The name of your workflow
on [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: https://hooks.slack.com/services/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
        if: always()
